apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: LoadBalancer
  ports:
    - name: port1
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: helloworld-app