apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: LoadBalancer
  ports:
    - name: http-port1
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: helloworld-app